name: crossfire
description: Cross-platform firebase API
version: 2.0.3
homepage: https://www.github.com/apptreesoftware/crossfire
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Matthew Smith <matthew.smith@apptree.cloud>

environment:
  sdk: '>=1.23.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
  build_runner: any
