name: crossfire_web
description: Cross-platform firebase API for browsers
version: 2.0.0+5
homepage: https://www.github.com/apptreesoftware/crossfire
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Matthew Smith <matthew.smith@apptreesoftware.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  crossfire: ^2.0.0
  jsifier: ^2.0.0
  firebase: ^5.0.0

dev_dependencies:
  test: ^1.3.0
