name: crossfire_flutter
description: Cross-platform firebase API for Flutter
version: 2.0.0+3
homepage: https://www.github.com/apptreesoftware/crossfire
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Matthew Smith <matthew.smith@apptree.cloud>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crossfire: ^2.0.0

  cloud_firestore: ^0.8.0
  # TODO: Make a PR
  # this branch allows switching between firebase apps at runtime
  firebase_auth:
    git:
      url: git://github.com/apptreesoftware/plugins
      path: packages/firebase_auth

  firebase_core: ^0.2.5
  firebase_storage: ^1.0.2
  firebase_database: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
